version: '3'

networks:
  nginx:
    driver: 'bridge'

volumes:
  nginxconfig:
    driver: ${VOLUMES_DRIVER}

services:

### NGINX PROXY ##################################

    nginx-proxy:
      image: nginxproxy/nginx-proxy
      container_name: nginx-proxy
      ports:
        - "443:443"
        - "80:80"
      restart: always
      environment:
        - VIRTUAL_PORT=443
        - HSTS=off
        - HTTPS_METHOD=nohttp
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./nginx-proxy/certs/:/etc/nginx/certs:rw
        - ./nginx-proxy/vhost/:/etc/nginx/vhost.d:rw
        - ./nginx-proxy/dhparam/:/etc/nginx/dhparam:rw
        - nginxconfig:/etc/nginx/conf.d
        - ./nginx-proxy/html/:/usr/share/nginx/html:rw
      networks:
        - nginx
