version: '3'

volumes:
  portainer_data:

services:

### PORTAINER ##################################

  portainerservice:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9001:9000"
